name: pokemon_card_price_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  new_version: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_slidable:
  intl:
  shared_preferences:
  animated_splash_screen: ^1.2.0

  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.11
  flutter_gen_runner:

flutter_icons:
  image_path: 'assets/images/app_icon.png'
  image_path_ios: 'assets/images/app_icon.png'
  android: false
  ios: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/splash.gif
    - assets/images/app_icon.png
    - assets/images/app_bar_1.jpeg
    - assets/ball/
